spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/LibraryMS}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:facebook.com}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET:myverylongsecretkeythatisatleast32chars}
  expiration: 86400000
